name: 'Argocd webhook notify'
description: 'This action send a github notification to argocd'
inputs:
  deployment_repo_path:
    description: 'The deployment repo path (ex: numerique-gouv/action-argocd-webhook-notification)'
    required: true
  argocd_webhook_secret:
    description: 'The argocd webhook secret (value of webhook.github.secret in argocd helm chart)'
    required: true
  argocd_url:
    description: 'The argocd url'
    required: true
runs:
  using: "composite"
  steps:
    -
      name: Notify argocd
      shell: bash
      run: |
        data='{"ref": "'$GITHUB_REF'","repository": {"html_url":"'$GITHUB_SERVER_URL'/${{ inputs.deployment_repo_path }}"}}'
        sig=$(echo -n ${data} | openssl dgst -sha256 -hmac "${{ inputs.argocd_webhook_secret }}" | awk '{print "X-Hub-Signature-256: sha256="$2}')
        curl -X POST -H 'X-GitHub-Event:push' -H "Content-Type: application/json" -H "${sig}" --data "${data}" "${{ inputs.argocd_url }}/api/webhook"
